excluded: 
  - Carthage

warning_threshold: 15

line_length:
warning: 120

function_parameter_count:
warning: 10
error: 15

file_length:
  warning: 400
  error: 500

nesting:
  type_level: 3

disabled_rules:
  - trailing_whitespace
  - class_delegate_protocol